
POST http://localhost:3003/reports
Content-Type: application/json

{
  "make": "Cheverolet",
  "model": "Corvette",
  "year": 2022,
  "mileage": 15000,
  "price": 20000,
  "latitude": 34.0522,
  "longitude": -118.2437
}

### Approve the report with ID 5
PATCH http://localhost:3003/reports/5
Content-Type: application/json

{
  "approved": true
}

### Get estimate
GET http://localhost:3003/reports?make=Ford&model=Mustang&year=2020&latitude=34.0522&longitude=-118.2437&mileage=10000
Content-Type: application/json