
### Create New User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Geovani",
  "email": "geovani@mail.com",
  "phone": "628323123",
  "password": "12123213123"
}

### Get All Users
GET http://localhost:3000/users?limit=1&offset=1
Content-Type: application/json

### Get One Users
GET http://localhost:3000/users/1
Content-Type: application/json


### Update One Users
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "name": "Felix Sr",
  "email": "felix@mail.com"
}

### Delete One Users
DELETE http://localhost:3000/users/2
Content-Type: application/json

