
### Create New User
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Geovani",
  "email": "geovani@mail.com",
  "phone": "628323123",
  "password": "12123213123"
}

### Get All Users
GET http://localhost:3000/users
Content-Type: application/json

### Get One Users
GET http://localhost:3000/users/1
Content-Type: application/json


### Update One Users
PATCH http://localhost:3000/users/8
Content-Type: application/json

{
  "password": "NewP@ssw0rd12345!"
}

### Recover One Users
PATCH http://localhost:3000/users/9/recover
Content-Type: application/json

### Delete One Users
DELETE http://localhost:3000/users/9?soft=true
Content-Type: application/json


### Create New Category
POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "electronic"
}

### Get All Categories
GET http://localhost:3000/categories
Content-Type: application/json

### Delete Categories
DELETE http://localhost:3000/categories/1
Content-Type: application/json



### Create New Products
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Ball",
  "price": 2.5,
  "categories": [
    { "id": 1 }
  ]
}

### Get Products
GET http://localhost:3000/products
Content-Type: application/json


### Create New Order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "customer": { "id": 6 },
  "items": [
    {
      "product": { "id": 1 },
      "quantity": 2
    }
  ]
}

### Get Orders
GET http://localhost:3000/orders
Content-Type: application/json

### Get Order Details
GET http://localhost:3000/orders/3
Content-Type: application/json

### Create New Payment
POST http://localhost:3000/payments/2
Content-Type: application/json

### Seeding the data
POST http://localhost:3000/seeding
Content-Type: application/json

### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "jarulf@mail.com",
  "password": "NewP@ssw0rd12345!"
}

### Login User
GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImlhdCI6MTc2ODQ3MjQ4MiwiZXhwIjoxNzY5MDc3MjgyfQ.y1vAqlW62bPhTwa-B8FHAXRMNOo60GraOb7WtrWd1Xs
Content-Type: application/json